@startuml

class Doctor {
    +id: int
    name: String
    birthday: Date
    genre: String
    email: String
    phone: String
}

class Patient {
    +id: int
    name: String
    genre: String
    birthday: Date
    email: String
    phone: String
    registerDate: Date
}

class MedicalRecord {
    +id: int
    patient: Patient
    diagnostic: String
    treatment: String
    updateDate: Date
}

class Appointment {
    +id: int
    patient: Patient
    doctor: Doctor
    date: Date
    typeAppointment: String
    appointmentStatus: String
}

class Payment {
    +id: int
    patient: Patient
    amount: Double
    paymentDate: Date
    paymetnMethod: String
}

class SatisfactionSurvey {
    +id: int
    patient: Patient
    doctor: Doctor
    score: int
    comments: String
    surveyDate: Date
}

class ExpenseControl {
    +id: int
    description: String
    expenseAmount: Double
    expenseDate: Date
}

class DocumentSinging {
    +id: int
    patient: Patient
    signingImage:
    signingDate: Date
}

Patient ---> MedicalRecord
Patient ---> Appointment
Patient ---> Payment
Patient ---> SatisfactionSurvey
Patient --->  DocumentSinging
Doctor ---> ExpenseControl
Appointment ---> Doctor
SatisfactionSurvey ---> Doctor



'Herencia/Generalización: extends o --> con una flecha hueca.
'Implementación/Realización: implements o ..> con flecha hueca discontinua.
'Composición: *-- con rombo relleno.
'Agregación: o-- con rombo vacío.
'Asociación: --> con flecha simple.
'Dependencia: ..> con línea discontinua y flecha simple.
