@startuml RelationalCorvent

entity Doctor {
    +id: int
    name: String
    birthday: Date
    genre: String
    email: String
    phone: String
}

entity Patient {
    +id: int
    name: String
    genre: String
    birthday: Date
    email: String
    phone: String
    registerDate: Date
}

entity MedicalRecord {
    +id: int
    patient: Patient
    diagnostic: String
    treatment: String
    updateDate: Date
}

entity Appointment {
    +id: int
    patient: Patient
    doctor: Doctor
    date: Date
    typeAppointment: String
    appointmentStatus: String
}

entity Payment {
    +id: int
    patient: Patient
    amount: Double
    paymentDate: Date
    paymetnMethod: String
}

entity SatisfactionSurvey {
    +id: int
    patient: Patient
    doctor: Doctor
    score: int
    comments: String
    surveyDate: Date
}

entity ExpenseControl {
    +id: int
    description: String
    expenseAmount: Double
    expenseDate: Date
}

entity DocumentSinging {
    +id: int
    patient: Patient
    signingImage:
    signingDate: Date
}

Patient ||--o{ Appointment
Patient ||--|| Payment
Patient ||--|| MedicalRecord
Patient ||--o{ SatisfactionSurvey
Doctor ||--|| ExpenseControl
Appointment ||--|| Doctor
Patient ||--|| DocumentSinging
SatisfactionSurvey ||--|| Doctor